# Generated by Django 5.2.13 on 2026-05-04 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type MIME')),
                ('category', models.CharField(choices=[('contract', 'Contrat'), ('legal', 'Juridique'), ('financial', 'Financier'), ('hr', 'RH'), ('technical', 'Technique'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('encrypted', 'Chiffré'), ('pending', 'En attente'), ('revoked', 'Révoqué')], default='encrypted', max_length=20, verbose_name='Statut')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Partagé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('upload', 'Upload document'), ('download', 'Téléchargement'), ('share', 'Partage'), ('delete', 'Suppression'), ('view', 'Consultation'), ('edit', 'Modification'), ('password_reset', 'Réinitialisation MDP'), ('mfa_enabled', 'MFA activé'), ('mfa_disabled', 'MFA désactivé')], max_length=30, verbose_name='Action')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Détail')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='user.document', verbose_name='Document concerné')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10, verbose_name='Statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='user.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': "Demande d'accès",
                'verbose_name_plural': "Demandes d'accès",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Lecture seule'), ('download', 'Téléchargement'), ('edit', 'Édition')], default='view', max_length=10, verbose_name='Permission')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Partagé le')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='user.document', verbose_name='Document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_sent', to=settings.AUTH_USER_MODEL, verbose_name='Partagé par')),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL, verbose_name='Partagé avec')),
            ],
            options={
                'verbose_name': 'Partage',
                'verbose_name_plural': 'Partages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Alerte')], default='info', max_length=10, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Ticket support',
                'verbose_name_plural': 'Tickets support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('file', models.FileField(upload_to='documents/versions/%Y/%m/', verbose_name='Fichier')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note de version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='user.document', verbose_name='Document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de document',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
