# Generated by Django 5.2.13 on 2026-05-07 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('global', 'Global - Tout le monde'), ('department', 'Département - Limité à certains services'), ('specific', 'Spécifique - Personnes précises')], default='specific', max_length=10, verbose_name='Type de diffusion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('departments', models.ManyToManyField(blank=True, related_name='documents_allowed', to='auth.group', verbose_name='Départements concernés')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user.document', verbose_name='Document')),
                ('users', models.ManyToManyField(blank=True, related_name='documents_shared', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs concernés')),
            ],
            options={
                'verbose_name': 'Permission de document',
                'verbose_name_plural': 'Permissions de documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
