# Generated by Django 5.2.13 on 2026-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_documentpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Type MIME'),
        ),
    ]
