# Generated by Django 5.2.13 on 2026-05-07 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_document_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpermission',
            name='permission_type',
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='permission_types',
            field=models.CharField(blank=True, choices=[], max_length=50, verbose_name='Types de diffusion'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_managed', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.department', verbose_name='Département parent')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('manager', 'Manager'), ('director', 'Directeur')], default='member', max_length=10, verbose_name='Rôle')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'arrivée")),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='user.department', verbose_name='Département')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Département utilisateur',
                'verbose_name_plural': 'Départements utilisateurs',
                'unique_together': {('user', 'department')},
            },
        ),
    ]
