# Generated by Django 5.2.13 on 2026-05-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_documentpermission_permission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpermission',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='documents_allowed', to='user.department', verbose_name='Départements concernés'),
        ),
        migrations.AlterField(
            model_name='documentpermission',
            name='permission_types',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Types de diffusion'),
        ),
    ]
