# Generated by Django 5.2.13 on 2026-05-13 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_documentpermission_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_key', models.TextField(verbose_name='Clé de chiffrement (JWK)')),
                ('encryption_iv', models.TextField(verbose_name="Vecteur d'initialisation")),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50, verbose_name='Algorithme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_key', to='user.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Clé de chiffrement',
                'verbose_name_plural': 'Clés de chiffrement',
            },
        ),
    ]
