# Generated by Django 5.2.13 on 2026-05-13 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_documentencryptionkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='changes_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Résumé des changements'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash SHA-256'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='user.document'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='documents/versions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='version_number',
            field=models.PositiveIntegerField(),
        ),
    ]
